DROP TABLE IF EXISTS TRANSFERENCIA_HISTORICO;
DROP TABLE IF EXISTS BENEFICIO;

CREATE TABLE BENEFICIO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR DECIMAL(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE NOT NULL,
  VERSION BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE TRANSFERENCIA_HISTORICO (
  ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  FROM_ID BIGINT NOT NULL,
  FROM_NOME VARCHAR(100) NOT NULL,
  TO_ID BIGINT NOT NULL,
  TO_NOME VARCHAR(100) NOT NULL,
  AMOUNT DECIMAL(15,2) NOT NULL,
  FROM_VALOR_FINAL DECIMAL(15,2) NOT NULL,
  TO_VALOR_FINAL DECIMAL(15,2) NOT NULL,
  EXECUTADO_EM TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_transf_executado_em ON TRANSFERENCIA_HISTORICO(EXECUTADO_EM DESC);
